### ISSUE TITLE
Correct the Magnetic Declination to show S amd E lat & lon

### ISSUE THREAD

**Issue by seabilwe** [kartoza/SAGTA#97]
The current MD is given in N/W lat & lon, the MD must be set for the southern hemishpere

**Comment by seabilwe** [comment]
This is updated:

![Image](https://github.com/user-attachments/assets/0fda766f-d644-481a-abe4-3eadcb46ef47)

@dimasciput can you assist with pushing the changes.

I updated the https://github.com/kartoza/SAGTA/blob/main/qgis_desktop_setup/qgis_scripts/magnetic_declination.py and the https://github.com/kartoza/SAGTA/blob/main/plugins/qgisserver/ServerExpression/__init__.py

**Comment by dimasciput** [comment]
@seabilwe I have updated the script in the lizmap server

**Comment by gubuntu** [comment]
The MD is apparently still wrong as per OP. Fix asap to give correct southern hemisphere declination

**Comment by seabilwe** [comment]
@dimasciput can you redeploy the magnetic declination scripts, they have the latest version of the MD updtaes

**Comment by dimasciput** [comment]
@seabilwe where is the updated script?

**Comment by seabilwe** [comment]
Here @dimasciput :

https://github.com/kartoza/SAGTA/blob/main/qgis_desktop_setup/qgis_scripts/magnetic_declination.py
https://github.com/kartoza/SAGTA/blob/main/plugins/qgisserver/ServerExpression/__init__.py

**Comment by seabilwe** [comment]
> Here [@dimasciput](https://github.com/dimasciput) :
> 
> https://github.com/kartoza/SAGTA/blob/main/qgis_desktop_setup/qgis_scripts/magnetic_declination.py https://github.com/kartoza/SAGTA/blob/main/plugins/qgisserver/ServerExpression/__init__.py

@dimasciput has this been deployed?

**Comment by seabilwe** [comment]
@gubuntu here is the updated script here: https://github.com/kartoza/SAGTA/pull/116
This is how it looks, from my local: 

![Image](https://github.com/user-attachments/assets/277db775-caf5-4613-8b31-4011679acadf)

Note: I will remove the formatting (i.e. W of TN)

**Comment by gubuntu** [comment]
how do you mean remove? remove formatting or text? It looks OK to me - what matters is that the numbers and directions are correct

**Comment by seabilwe** [comment]
@gubuntu what I meant to say was: In the MDL, the magnetic declination (MD) is presented as  23°58′ W, and the mean annual change is 0° 6′ E instead of 0° 6′ E per year and 23°58′ west of True North.

So I will change how the two are presented

**Comment by Jeremy-Prior** [comment]
I believe this is linked to the MD issue found in the map layout as answered here: https://github.com/kartoza/SAGTA/issues/110#issuecomment-2851236209

CC: @seabilwe

**Comment by seabilwe** [comment]
I have noted that, thanks @Jeremy-Prior

**Comment by gubuntu** [comment]
if done then close @seabilwe
